/** Public JSON envelopes; kept outside the translation message compiler. */
export const nativeFormatExamples = {
  brushFormat: '{\n  "format": "focale-brush-presets",\n  "version": 1,\n  "presets": [\n    {\n      "id": "brush.user.example",\n      "name": "Soft round",\n      "settings": {\n        "size": 32,\n        "hardness": 0.8,\n        "spacingRatio": 0.1,\n        "shape": "circle"\n      }\n    }\n  ],\n  "assets": [],\n  "patterns": []\n}',
  patternFormat: '{\n  "format": "focale-pattern-presets",\n  "version": 1,\n  "presets": [\n    {\n      "id": "user.example",\n      "name": "Blue fabric",\n      "patternId": "pattern.2.1.9e2b63675440c0d9",\n      "groupPath": [\n        "Materials",\n        "Fabric"\n      ]\n    }\n  ],\n  "assets": [\n    {\n      "id": "pattern.2.1.9e2b63675440c0d9",\n      "width": 2,\n      "height": 1,\n      "rgba": "ChTI/8zq/4A="\n    }\n  ]\n}',
  shapeFormat: '{\n  "format": "focale-custom-shape-presets",\n  "version": 1,\n  "presets": [\n    {\n      "version": 1,\n      "id": "shape.user.01234567-89ab-cdef-0123-456789abcdef",\n      "name": "Leaf",\n      "sourceAspectRatio": 2,\n      "groupPath": [\n        "Nature"\n      ],\n      "sortOrder": 4,\n      "outline": {\n        "id": "shape.user.01234567-89ab-cdef-0123-456789abcdef",\n        "name": "Leaf",\n        "subpaths": [\n          {\n            "closed": true,\n            "anchors": [\n              {\n                "x": 0,\n                "y": 0.5,\n                "outX": 0.2,\n                "outY": -0.5\n              },\n              {\n                "x": 1,\n                "y": 0.5,\n                "inX": -0.2,\n                "inY": -0.5\n              },\n              {\n                "x": 0.5,\n                "y": 1\n              }\n            ]\n          }\n        ]\n      }\n    }\n  ]\n}',
  styleFormat: '{\n  "format": "focale-style-presets",\n  "version": 1,\n  "presets": [\n    {\n      "id": "style.user.example",\n      "name": "Editorial shadow",\n      "groupPath": [\n        "Editorial"\n      ],\n      "style": {\n        "fillOpacity": 0.8,\n        "effects": [\n          {\n            "kind": "dropShadow",\n            "enabled": true,\n            "color": 4279383126,\n            "opacity": 0.65,\n            "angle": 120,\n            "distance": 12,\n            "spread": 0,\n            "size": 9\n          }\n        ]\n      }\n    }\n  ]\n}',
  swatchFormat: '{\n  "format": "focale-color-swatches",\n  "version": 1,\n  "presets": [\n    {\n      "id": "swatch.user.black",\n      "name": "Black",\n      "color": 4278190080,\n      "groupPath": [\n        "Studio"\n      ]\n    }\n  ]\n}',
  gradientFormat: '{\n  "format": "focale-gradient-presets",\n  "version": 1,\n  "presets": [\n    {\n      "id": "gradient.user.example",\n      "name": "Editorial",\n      "groupPath": [\n        "Studio"\n      ],\n      "gradient": {\n        "interpolation": "perceptual",\n        "stops": [\n          {\n            "position": 0.0,\n            "color": 4279246896,\n            "midpoint": 0.4\n          },\n          {\n            "position": 1.0,\n            "color": 4292927712\n          }\n        ]\n      }\n    }\n  ]\n}',
  curveFormat: '{\n  "format": "focale-curve-presets",\n  "version": 1,\n  "presets": [\n    {\n      "id": "curve.user.identity",\n      "name": "Identity",\n      "curves": {\n        "rgb": [\n          0,\n          1,\n          0,\n          1\n        ],\n        "red": [\n          0,\n          1,\n          0,\n          1\n        ],\n        "green": [\n          0,\n          1,\n          0,\n          1\n        ],\n        "blue": [\n          0,\n          1,\n          0,\n          1\n        ]\n      }\n    }\n  ]\n}',
  actionFormat: '{\n  "format": "focale-action-set",\n  "version": 1,\n  "set": {\n    "id": "set.example",\n    "name": "Web preparation",\n    "actions": [\n      {\n        "id": "action.example",\n        "name": "Resize and sharpen",\n        "functionKey": 4,\n        "shiftModifier": true,\n        "commandModifier": false,\n        "color": "blue",\n        "steps": [\n          {\n            "id": "step.resize",\n            "enabled": true,\n            "operation": "document.resizeImage",\n            "parameters": {\n              "width": 1600,\n              "height": 900\n            }\n          }\n        ]\n      }\n    ]\n  },\n  "sampledTips": [],\n  "patterns": []\n}',
} as const
